a : o
b : d
c : u
d : b
e : c
f : z
g : f
h : a
i : (('b',),)
j : j
k : s
l : l
m : r
n : (('e', 'p', 'r'),)
o : ((('w',), ('j',), ('i',)), ('w', 'j', 'i'))
p : i
q : ('e', 'w')
r : (('z',), ('x',), ('k',))
s : (((('o',),),),)
t : m
u : (((('e', 'd', 'b'),),),)
v : y
w : k
x : (('r',), ('q',), ('v',))
y : h
z : v

abcdefghijklmnopqrstuvwxyz
----------------○--------- 0
----------------○--------- 1 0
